### ISSUE TITLE
Can't fully create a new API under an existing group

### ISSUE THREAD

**Issue by raaizik** [red-hat-storage/ocs-operator#2192]
Files seem to be getting generated (including a controller though it's explicitly disabled in the command below), but some functions are missing. The error is the following:
```
% operator-sdk create api --group ocs --version v1 --kind someKind --controller false
FATA[0003] failed to create API: unable to run post-scaffold tasks of "go.kubebuilder.io/v2": exit status 1 
```

**Comment by raaizik** [comment]
A solution is suggested in #2191

**Comment by iamniting** [comment]
Hi Racheli, The fix is merged you create a scaffolding now.
